ARG BASE_IMAGE=vllm/vllm-openai:v0.21.0
FROM ${BASE_IMAGE}

ARG COMMON_WORKDIR=/app

WORKDIR ${COMMON_WORKDIR}

# Step 1: Setup - Install system dependencies
RUN apt-get update && \
    apt-get install -y git jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${COMMON_WORKDIR}/vllm-omni

RUN git clone -b mbala/cosmos3-v0.21.0 https://github.com/MaciejBalaNV/vllm.git; cd vllm; VLLM_VERSION_OVERRIDE=0.21.0 VLLM_USE_PRECOMPILED=1 uv pip install --python "$(python3 -c 'import sys; print(sys.executable)')" --no-cache-dir "." --torch-backend=auto
# Step 2: Copy vllm-omni code and install
COPY . ${COMMON_WORKDIR}/vllm-omni
RUN cd ${COMMON_WORKDIR}/vllm-omni && VLLM_OMNI_VERSION_OVERRIDE=0.21.0 uv pip install --python "$(python3 -c 'import sys; print(sys.executable)')" --no-cache-dir "."

RUN uv pip install --python "$(python3 -c 'import sys; print(sys.executable)')" cosmos-guardrail
#RUN git clone -b mbala/cosmos3-v0.21.0 https://github.com/MaciejBalaNV/vllm.git; cd vllm; VLLM_USE_PRECOMPILED=1 uv pip install --python "$(python3 -c 'import sys; print(sys.executable)')" --no-cache-dir "." --torch-backend=auto

RUN ln -sf /usr/bin/python3 /usr/bin/python

ENTRYPOINT []